#!/bin/sh
. ts-test-unit

setup () {
  set -ex
}

test_fail () {
true
false
true
}

test_exit_fail () {
exit 8
}

test_assert_status_fail () {
assert_status 0 1
}

test_assert_status_fail_with_str_input () {
assert_status "a" "a"
}

test_assert_output_fail () {
assert_output "hello w0rld" "hello world"
}

test_assert_output_from_stdin_fail () {
assert_output - "hello world" <<doc
hello w0rld
doc
}

run_test
