#!/bin/sh
. ts-test-unit

setup () {
  set -ex
}

test_fail () {
true
false
true
}

test_exit_fail () {
exit 8
}

test_assert_status_fail () {
assert_status 0 1
}

test_assert_status_fail_with_str_input () {
assert_status "a" "a"
}

test_assert_output_fail () {
assert_output "hello w0rld" "hello world"
}

test_assert_output_from_stdin_fail () {
assert_output - "hello world" <<doc
hello w0rld
doc
}

#
# assert_match tests
#

test_assert_match_fail () {
assert_match "hello.+rld" "hell0 world"
}

test_assert_match_pattern_from_stdin_fail () {
assert_match - "hell0 world" <<doc
hello.+rld
doc
}

test_assert_match_output_from_stdin_fail () {
assert_match "hello.+rld" - <<doc
hell0 world
doc
}


run_test
