#!/bin/sh
. ts-test-unit

setup () {
set -x
}

test_exit_pass () {
exit
}

#
# assert test
#

test_assert_pass () {
assert true
}

#
# assert_status tests
#

test_assert_status_pass () {
assert_status 0 0
}

#
# assert_output tests
#

test_assert_output_pass () {
assert_output "hello world" "hello world"
}

test_assert_output_from_stdin_pass () {
assert_output - "hello world" <<doc
hello world
doc
}

test_assert_output_actual_from_stdin_pass () {
assert_output "hello world" - <<doc
hello world
doc
}

test_assert_output_with_numbers_pass () {
assert_output 0 0
assert_output "0" "0"
}

#
# assert_match tests
#

test_assert_match_pass () {
assert_match "hello.+rld" "hello world"
}

test_assert_match_pattern_from_stdin_pass () {
assert_match - "hello world" <<doc
hello.+rld
doc
}

test_assert_match_output_from_stdin_pass () {
assert_match "hello.+rld" - <<doc
hello world
doc
}

run_tests
