#!/bin/sh
. ts-test-unit

setup () {
  set -ex
}

test_pass () {
true
true
true
}

test_exit_pass () {
exit
}

test_assert_status_pass () {
assert_status 0 0
}

test_assert_status_pass_with_str_input () {
assert_status "0" "0"
}

test_assert_output_pass () {
assert_output "hello world" "hello world"
}

test_assert_output_from_stdin_pass () {
assert_output - "hello world" <<doc
hello world
doc
}

#
# assert_match tests
#

test_assert_match_pass () {
assert_match "hello.+rld" "hello world"
}

test_assert_match_pattern_from_stdin_pass () {
assert_match - "hello world" <<doc
hello.+rld
doc
}

test_assert_match_output_from_stdin_pass () {
assert_match "hello.+rld" - <<doc
hello world
doc
}

run_test
