#!/bin/sh

#
# EXAMPLES
#

test_pass () {
  true
}

test_assert_status_pass () {
  true
  assert_status 0 $?
}

test_assert_output_style_one () {
  out=$(printf "hello world")
  assert_output "hello world" "$out"
}

test_assert_output_style_two () {
  printf "hello world" | assert_output "hello world"
}

#
# GOTCHAS
#

test_this_has_a_bug_and_does_not_fail () {
  printf "0" | assert_output "1"
  assert true
}

. ts

