#!/bin/sh
############################################################################
if ! which ts > /dev/null
then
  printf "%s\n\n%s\n\n" \
  'Could not find ts.  Try adding the ts bin dir to your PATH.' \
  '  export PATH="$(pwd)/bin:$PATH"'
  exit 1
fi

. ts

setup () {
set -x

# ensure ts called in the tests will not collide with the suite itself
export TS_TMP_DIR="$test_dir"
}

test_ts_h_prints_help () {
out=`ts -h`
assert_match "usage:" "$out"
}

test_ts_does_not_print_passing_tests () {
out=`ts test/ts/pass 2>/dev/null`
assert_output "" "$out"
}

test_ts_prints_failing_tests () {
out=`ts test/ts/fail 2>/dev/null`
assert_output - "$out" <<out
[test/ts/fail:8] test_fail
F
out
}

test_ts_prints_all_test_for_verbose () {
out=`ts -v test/ts/pass test/ts/fail 2>/dev/null`
assert_output - "$out" <<out
[test/ts/pass:8] test_pass
P
[test/ts/fail:8] test_fail
F
out
}

test_ts_assertions_pass () {
out=`ts test/assertions/pass 2>&1 | tail -n 1`
assert_match "[0-9]{1,} pass 0 fail" "$out"
}

test_ts_assertions_fail () {
out=`ts test/assertions/fail 2>&1 | tail -n 1`
assert_match "0 pass [0-9]{1,} fail" "$out"
}
