#!/bin/sh
. ts

setup () {
set -x
}

test_exit_fail () {
exit 8
}

test_return_fail () {
false
}

#
# assert test
#

test_assert_fail () {
assert false
}

#
# assert_status tests
#

test_assert_status_fail () {
assert_status 0 1
}

#
# assert_output tests
#

test_assert_output_fail () {
assert_output "hello world" "hell0 world"
}

test_assert_output_expected_from_stdin_fail () {
printf "hello world" | assert_output - "hell0 world"
}

test_assert_output_actual_from_stdin_fail () {
printf "hello w0rld" | assert_output "hello world" -
}

test_assert_output_with_newline_fail () {
printf "hello w0rld\n" | assert_output "\
hello world
" -
}

test_assert_output_with_numbers_fail () {
assert_output 0 1
assert_output "0" "1"
}

test_assert_output_with_pattern_fail () {
assert_output "hello.+rld" "hello world"
}

#
# assert_match tests
#

test_assert_match_fail () {
assert_match "hello.+rld" "hell0 world"
}

test_assert_match_pattern_from_stdin_fail () {
printf "hello.+rld" | assert_match - "hell0 world"
}

test_assert_match_output_from_stdin_fail () {
printf "hell0 world" | assert_match "hello.+rld" -
}
