#!/bin/sh
. ts

setup () {
set -x
}

test_exit_fail () {
exit 8
}

test_return_fail () {
false
}

#
# assert test
#

test_assert_fail () {
assert false
}

#
# assert_status tests
#

test_assert_status_fail () {
assert_status 0 1
}

#
# assert_output tests
#

test_assert_output_fail () {
assert_output "hello world" "hell0 world"
}

test_assert_output_expected_from_stdin_fail () {
assert_output - "hell0 world" <<doc
hello world
doc
}

test_assert_output_actual_from_stdin_fail () {
assert_output "hello world" - <<doc
hell0 world
doc
}

test_assert_output_with_pattern_fail () {
assert_output "hello.+rld" "hello world"
}

#
# assert_match tests
#

test_assert_match_fail () {
assert_match "hello.+rld" "hell0 world"
}

test_assert_match_pattern_from_stdin_fail () {
assert_match - "hell0 world" <<doc
hello.+rld
doc
}

test_assert_match_output_from_stdin_fail () {
assert_match "hello.+rld" - <<doc
hell0 world
doc
}
