#!/bin/sh
. ts

setup () {
set -x
}

test_exit_pass () {
exit
}

test_return_pass () {
true
}

#
# assert test
#

test_assert_pass () {
assert true
}

#
# assert_status tests
#

test_assert_status_pass () {
assert_status 0 0
}

#
# assert_output tests
#

test_assert_output_pass () {
assert_output "hello world" "hello world"
}

test_assert_output_from_stdin_pass () {
printf "hello world" | assert_output - "hello world"
}

test_assert_output_actual_from_stdin_pass () {
printf "hello world" | assert_output "hello world" -
}

test_assert_output_with_implicit_stdin_pass () {
printf "hello world" | assert_output "hello world"
}

test_assert_output_with_newline_pass () {
printf "hello world\n" | assert_output "\
hello world
" -
}

test_assert_output_with_numbers_pass () {
assert_output 0 0
assert_output "0" "0"
}

#
# assert_match tests
#

test_assert_match_pass () {
assert_match "hello.+rld" "hello world"
}

test_assert_match_pattern_from_stdin_pass () {
printf "hello.+rld" | assert_match - "hello world"
}

test_assert_match_actual_from_stdin_pass () {
printf "hello world" | assert_match "hello.+rld" -
}

test_assert_match_with_implicit_stdin_pass () {
printf "hello world" | assert_match "hello.+rld"
}
