#!/bin/sh

# FAIL
#   unequal output:
#   1c1
#   < abc
#   ---
#   > abc
#   \ No newline at end of file
test_newline_is_missing_so_this_fails () {
out=$(echo abc)

assert_output "\
abc
" "$out"
}

# PASS
#   unequal output:
#   1c1
#   < 1
#   \ No newline at end of file
#   ---
#   > 0
#   \ No newline at end of file
test_multiple_asserts_not_failing_as_intended () {
  assert_output "1" "0"
  assert_output "0" "0"
}

# FAIL
#   unequal output:
#   1c1
#   < 1
#   \ No newline at end of file
#   ---
#   > 0
#   \ No newline at end of file
test_this_fails_as_expected () {
  printf "0" | assert_output "1" &&
  assert_output "0" "0"
}

# FAIL
#   unequal output:
#   1c1
#   < 1
#   \ No newline at end of file
#   ---
#   > 0
#   \ No newline at end of file
#   expected status 0 but was 1 (checking the pipeline)
test_this_also_fails_as_expected () {
  printf "0" | assert_output "1"
  assert_status "0" $? "checking the pipeline"
  assert_output "0" "0"
}

. test/helper
. ts
