#!/bin/sh

# PASS
test_newline_is_now_accounted_for () {
out=$(echo abc; printf x)

assert_output "\
abc
" "${out%x}"
}

# PASS
test_another_newline_strategy () {
echo abc | assert_output "\
abc
"
}

. test/helper
. ts
