#!/bin/sh

# PASS
test_newline_is_now_accounted_for () {
out=$(echo abc; printf x)

assert_output "\
abc
" "${out%x}"
}

# PASS
test_another_newline_strategy () {
echo abc | assert_output "\
abc
"
}

# PASS
#   unequal output:
#   1c1
#   < 1
#   \ No newline at end of file
#   ---
#   > 0
#   \ No newline at end of file
test_this_has_a_bug_and_does_not_fail () {
  printf "0" | assert_output "1"
  assert_output "0" "0"
}

. test/helper
. ts
