#!/bin/sh
# pick a shell, any (POSIX) shell

setup () {              # optional setup
  mkdir -p "$ts_test_dir"
}

teardown () {           # optional teardown
  rm -r "$ts_test_dir"
}

test_pass () {          # write tests named like "test_"
  true                  # return 0 to pass.
}

. test/helper
. ts
