#!/bin/sh               # pick a shell, any (POSIX) shell

setup () {              # optional setup
  mkdir -p "$test_dir"
}

teardown () {           # optional teardown
  rm -r "$test_dir"
}

test_pass () {          # write tests named like "test_"
  true                  # return 0 to pass.
}

. ts
