#!/bin/sh

test_a () {
  printf "a"
  printf "A" >&2
  true
}

test_b () {
  printf "b"
  printf "B" >&2
  true
}

test_c () {
  printf "c"
  printf "C" >&2
  false
}

test_s () {
  skip "s"
  false
}

. test/helper
. ts
