#!/bin/sh

test_exit_fail () {
exit 8
}

test_return_fail () {
false
}

#
# assert_status tests
#

test_assert_status_fail () {
assert_status 0 1
}

#
# assert_output tests
#

test_assert_output_fail () {
assert_output "hello world" "hell0 world"
}

test_assert_output_expected_from_stdin_fail () {
printf "hello world" | assert_output - "hell0 world"
}

test_assert_output_actual_from_stdin_fail () {
printf "hello w0rld" | assert_output "hello world" -
}

test_assert_output_with_implicit_stdin_fail () {
printf "hello w0rld" | assert_output "hello world"
}


#
# combinations
#

test_multiple_asserts_fail_early () {
  assert_status 0 1
  assert_output "0" "0"
}

test_multiple_asserts_fail_late () {
  assert_status 0 0
  assert_output "0" "1"
}

. ts
