#!/bin/sh
. test/helper

# PASS
test_exit_pass () {
exit
}

# PASS
test_return_pass () {
true
}

# PASS
test_assert_status_pass () {
assert_status 0 0
}

# PASS
test_assert_status_pass_with_message () {
assert_status 0 0 "message"
}

# PASS
test_assert_output_pass () {
assert_output "hello world" "hello world"
}

# PASS
test_assert_output_from_stdin_pass () {
printf "hello world" | assert_output - "hello world"
}

# PASS
test_assert_output_actual_from_stdin_pass () {
printf "hello world" | assert_output "hello world" -
}

# PASS
test_assert_output_with_implicit_stdin_pass () {
printf "hello world" | assert_output "hello world"
}

# PASS
test_multiple_asserts_pass () {
  assert_status 0 0
  assert_output "0" "0"
}

. ts
