#!/bin/sh
#
# FAIL
#   in setup
#   in test
#   in teardown
#
. test/helper

setup () {
  printf "in setup\n"
}

teardown () {
  printf "in teardown\n"
  false
}

test_return_fail_in_teardown () {
  printf "in test\n"
}

. ts
