#!/bin/sh
. test/helper

# PASS
test_common () {
true
}

# PASS
test_with_whitespace 	 () {
true
}

# PASS
test_without_whitespace() {
true
}

# PASS
 	 test_leading_whitespace () {
true
}

# PASS
test_oneline () { true; }

# PASS
test_subshell () (
true
)

# PASS
test_subshell_oneline () ( true )

. ts
