.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TS" "1" "September 2012" "1.0.0-beta" ""
.
.SH "NAME"
\fBts\fR \- run ts shell test scripts
.
.SH "SYNOPSIS"
\fBts\fR \fIoptions\fR TEST_SCRIPT\.\.\.
.
.P
\fB[\./test_script]\fR \fIoptions\fR TESTS\.\.\.
.
.SH "DESCRIPTION"
\fBts\fR provides functions for writing tests in shell\. The test scripts can be run individually or in a batch format using \fBts\fR as a command\.
.
.P
\fBts\fR makes a test directory available on a per\-test basis so it\'s easy to sandbox tests that write or manipulate files\. \fBts\fR tries to use POSIX exclusively and so should (hopefully) work on any POSIX\-compliant system\.
.
.SH "TEST SCRIPTS"
The \fBts\fR command expects script files that define test cases\. Test scripts have the following form:
.
.IP "" 4
.
.nf

[\./example]
#!/bin/sh               # pick a shell, any (POSIX) shell

setup () {              # optional setup
  mkdir \-p "$test_dir"
}

teardown () {           # optional teardown
  rm \-r "$test_dir"
}

test_true () {          # write tests named like "test_"
  true                  # return 0 to pass\.
}

\[char46] ts                    # source ts to run the tests
.
.fi
.
.IP "" 0
.
.P
To run, use any of:
.
.IP "" 4
.
.nf

ts example              # run multiple test scripts
\[char46]/example               # run a single test script
\[char46]/example test_a_thing  # run a single test
.
.fi
.
.IP "" 0
.
.P
See the FUNCTIONS, EXAMPLES, and TROUBLESHOOT sections for more details\.
.
.SH "OPTIONS"
These options control how \fBts\fR operates:
.
.TP
\fB\-a\fR
Show passing outputs, which are normally filtered\.
.
.TP
\fB\-c\fR
Colorize output\. (green/red/yellow \- pass/fail/not\-executable)
.
.TP
\fB\-d\fR
Debug mode\. Turns on xtrace (set \-x) for the tests and enables \-v\.
.
.TP
\fB\-h\fR
Prints help\.
.
.TP
\fB\-m\fR
Monitor output\. Provide a ticker indicating the progress of tests and print a summary\. Monitor is the default\.
.
.TP
\fB\-r\fR
Remove the tmp dir on complete\. Removal is done using \fBrm \-r\fR\.
.
.TP
\fB\-s\fR
Stream output\. Show test progress as it happens\. No summary is printed\.
.
.TP
\fB\-t\fR
Set the test tmp dir (default tmp)\. The test\-specific directories are be located under this directory\.
.
.TP
\fB\-v\fR
Verbose output\. Enables \fBts\fR to display stderr for the tests (normally only stdout is shown)\.
.
.SH "FUNCTIONS"
Functions provided by \fBts\fR\.
.
.TP
\fBsetup\fR:
.
.IP
A setup function run before each test\.
.
.TP
\fBteardown\fR:
.
.IP
A teardown function run after each test\.
.
.IP
\fBts\fR ensures teardown runs by setting a trap for EXIT signals during setup and the actual test\. As a result, EXIT traps in tests can prevent teardown\.
.
.TP
\fBassert_status EXPECTED ACTUAL\fR:
.
.IP
Exit 1 unless the numbers EXPECTED and ACTUAL are the same\. This assertion is almost never necessary\.
.
.TP
\fBassert_output EXPECTED ACTUAL\fR:
.
.IP
Exit 1 unless the variables EXPECTED and ACTUAL are the same\. Reads from stdin for \'\-\'\. Also reads ACTUAL from stdin if ACTUAL is unspecified\.
.
.IP
Using assert_output in a pipeline is often convenient, but be careful you don\'t expect a failing assert_output to exit your test case as, in that case, it will only exit the pipeline\. See the EXAMPLES section for more details\.
.
.P
\fBts\fR reserves all function names starting with \'ts_\' for internal use\.
.
.SH "VARIABLES"
Variables provided by \fBts\fR at runtime\. Feel free to use any of them but treat them as read\-only\.
.
.TP
\fBtest_file\fR
The name of the current test script being run\.
.
.TP
\fBtest_case\fR
The basename of the test file, minus the extname\.
.
.TP
\fBtest_lineno\fR
The line number where the current test is defined\.
.
.TP
\fBtest_name\fR
The name of the current test\.
.
.TP
\fBtest_dir\fR
The test\-specific directory\.
.
.IP
The test dir is \'tmp_dir/test_case\'\. \fBts\fR does not create this directory automatically\. Add that functionality in the setup function as needed\.
.
.P
\fBts\fR reserves all variables starting with \'ts_\' for internal use\.
.
.SH "ENVIRONMENT"
Default \fBts\fR behavior can be set via environment variables\. Options provided to \fBts\fR override these defaults\.
.
.TP
\fBTS_USR_DIR\fR (pwd)
The user dir\. Used to determine the ts tmp dir\.
.
.TP
\fBTS_TMP_DIR\fR ($TS_USR_DIR/tmp)
The base tmp dir\.
.
.TP
\fBTS_COLOR\fR (false)
Set to "true" to enable color\.
.
.TP
\fBTS_DEBUG\fR (false)
Set to "true" to enable debug mode\.
.
.TP
\fBTS_REMOVE_TMP_DIR\fR (false)
Set to "true" to remove tmp dir\.
.
.TP
\fBTS_TESTS_IN_SOURCE\fR (false)
Set to "true" to look in source files (ie \fB\. file\fR or \fBsource file\fR) for tests\. Typically set per\-file before the source lines\.
.
.P
In addition these variables adjust the color output\.
.
.TP
\fBTS_PASS\fR (green)
Passing tests\.
.
.TP
\fBTS_FAIL\fR (red)
Failing tests\.
.
.TP
\fBTS_NOEX\fR (yellow)
Non\-executable test files\.
.
.TP
\fBTS_NORM\fR (normal)
The normal output color\.
.
.P
For example to turn failures blue:
.
.IP "" 4
.
.nf

export TS_FAIL=$(printf "%b" "\e033[0;34m")
.
.fi
.
.IP "" 0
.
.P
\fBts\fR reserves all variables starting with \'TS_\' for internal use\.
.
.SH "EXAMPLES"
Basic usage:
.
.IP "" 4
.
.nf

[\./example]
#!/bin/sh

test_arbitrary_function () {
  echo abc | grep \-q b
}

test_assert_status () {
  false
  assert_status 1 $?
}

test_assert_output_style_one () {
  out=$(printf "hello world")
  assert_output "hello world" "$out"
}

test_assert_output_style_two () {
  printf "hello world" | assert_output "hello world"
}

test_assert_output_style_three () {
printf "hello world\en" | assert_output "\e
hello world
"
}

\[char46] ts
.
.fi
.
.IP "" 0
.
.P
Run like:
.
.IP "" 4
.
.nf

chmod +x example
ts example
.
.fi
.
.IP "" 0
.
.SH "TROUBLESHOOT"
\fBMy tests aren\'t running\fR
.
.P
Be sure you added \fB\. ts\fR at the end of your script\.
.
.P
\fBMy tests are failing\fR
.
.P
\fB1)\fR Are you incrementing a variable in a loop in a pipeline?
.
.P
See http://mywiki\.wooledge\.org/BashFAQ/024\.
.
.P
\fB2)\fR Is a newline missing from a variable?
.
.P
Subshells chomp the last newline off of a command\.
.
.IP "" 4
.
.nf

test_newline_is_missing_so_this_fails () {
out=$(echo abc)

assert_output "\e
abc
" "$out"
}
.
.fi
.
.IP "" 0
.
.P
One way around this is to print a sacrificial non\-newline character\.
.
.IP "" 4
.
.nf

test_newline_is_now_accounted_for () {
out=$(echo abc; printf x)

assert_output "\e
abc
" "${out%x}"
}
.
.fi
.
.IP "" 0
.
.P
Another way is to pipe into assert_output\.
.
.IP "" 4
.
.nf

test_another_newline_strategy () {
echo abc | assert_output "\e
abc
"
}
.
.fi
.
.IP "" 0
.
.P
\fBMy tests aren\'t failing\fR
.
.P
\fB1)\fR Are you using asserts in a pipeline?
.
.P
\fBts\fR assert methods exit failure (rather than return) so this will fail\.
.
.IP "" 4
.
.nf

test_multiple_asserts_failing_as_intended () {
  assert_output "1" "0"
  assert_output "0" "0"
}
.
.fi
.
.IP "" 0
.
.P
However the assert methods in a pipeline will exit the pipeline instead of the test method so this will not fail\.
.
.IP "" 4
.
.nf

test_this_has_a_bug_and_does_not_fail () {
  printf "0" | assert_output "1"
  assert_output "0" "0"
}
.
.fi
.
.IP "" 0
.
.P
One way around this is to \fBset \-e\fR in your setup or at the start of the test so that any failing command (including a pipeline) will cause the function to exit in failure\.
.
.IP "" 4
.
.nf

test_this_now_fails_as_expected () {
  set \-e
  printf "0" | assert_output "1"
  assert_output "0" "0"
}
.
.fi
.
.IP "" 0
.
.P
Another way is to && all the asserts at the end of the test\.
.
.IP "" 4
.
.nf

test_this_also_fails_as_expected () {
  printf "0" | assert_output "1" &&
  assert_output "0" "0"
}
.
.fi
.
.IP "" 0
.
.P
\fBWeirdness with TS_TESTS_IN_SOURCE\fR
.
.P
Looking for tests in source\'d files does not work if you add additional arguments after the file name\. This undesirable limitation occurs because the lookup algorithm can\'t distinguish when a file with a space ends and the arguments begin\.
.
.P
This would cause \fBts\fR to look for tests in these files: "file one", "a", "b", "c" (and likely show up as error noise in the output)\.
.
.IP "" 4
.
.nf

TS_TESTS_IN_SOURCE=true
source "file one" a b c
.
.fi
.
.IP "" 0
.
.P
If you must do something like this, then try using set with source:
.
.IP "" 4
.
.nf

TS_TESTS_IN_SOURCE=true
set a b c
source "file one"
.
.fi
.
.IP "" 0
.
.P
Incidentally this weirdness is why TS_TESTS_IN_SOURCE is not enabled by default \-\- advanced users knowing this limitation can easily opt\-in to use it\. Also note that shells typically do not check for circular sources and neither does \fBts\fR, so check that for a hanging script\.
.
.P
\fBTeardown isn\'t running\fR
.
.P
Are you setting an EXIT trap? \fBts\fR uses an EXIT trap to ensure that teardown runs even when setup or a test exits\. Resetting an EXIT trap can prevent teardown from running\.
.
.IP "" 4
.
.nf

test_teardown_will_not_run () {
  trap \- EXIT
  exit 1
}
.
.fi
.
.IP "" 0
.
.SH "INSTALLATION"
Add \fBts\fR to your PATH (or execute it directly)\. A nice way of doing so is to clone the repo and add the bin dir to PATH\. This allows easy updates via \fBgit pull\fR and should make the manpages available via \fBman ts\fR\.
.
.IP "" 4
.
.nf

git clone git://github\.com/thinkerbot/ts\.git
export PATH="$PATH:$(pwd)/ts/bin"
.
.fi
.
.IP "" 0
.
.SH "DEVELOPMENT"
Clone the repo as above\. To run the tests (written in \fBts\fR):
.
.IP "" 4
.
.nf

ts test/suite
.
.fi
.
.IP "" 0
.
.P
To generate the manpages:
.
.IP "" 4
.
.nf

make manpages
.
.fi
.
.IP "" 0
.
.P
Report bugs here: http://github\.com/thinkerbot/ts/issues\.
.
.SH "COPYRIGHT"
TS is Copyright (C) 2011 Simon Chiang \fIhttp://github\.com/thinkerbot\fR
